integrate vp to campaign
valkyrieprotocol/contracts pull request #7
Opened 2022-02-09 07:00 UTC by path0509

2022-02-09 07:15 UTC, jdekim43 requested changes

2022-02-09 07:15 UTC, jdekim43 commented on contracts/campaign/src/executions.rs
> +    if let Some(vp_burn_amount) = vp_burn_amount {
pending 일 때만 변경할 수 있게 해야하지 않을까요?

2022-02-09 07:15 UTC, jdekim43 commented on contracts/campaign/src/executions.rs
> +                amount: campaign_config.vp_burn_amount * qualify_result.vp_burn_rate,
vp 도 참여에 따라서 번되는 수량이 달라져야하는건가요?

2022-02-09 07:15 UTC, jdekim43 commented on contracts/campaign_manager/src/entrypoints.rs
> +    migrations::v1_0_8(deps, env, msg)
cw2 사용해서 버전관리를 하고 필요한 마이그레이션을 모두 수행할 수 있게 수정해주실 수 있나요?

2022-02-09 07:15 UTC, jdekim43 commented on packages/valkyrie/src/campaign_manager/execute_msgs.rs
> +    pub vp_token:String,
띄어쓰기 해주세요.

2022-02-09 07:15 UTC, jdekim43 commented on contracts/campaign/src/executions.rs
> +                amount: campaign_config.vp_burn_amount * qualify_result.vp_burn_rate,
burn_rate 가 1보다 작은지 검증하는 로직이 추가되어야하고 
다른 rate 도 확인이 필요합니다.

2022-02-09 07:19 UTC, path0509 commented on contracts/campaign/src/executions.rs
> +    if let Some(vp_burn_amount) = vp_burn_amount {
수정하였음.

2022-02-09 07:20 UTC, path0509 commented on packages/valkyrie/src/campaign_manager/execute_msgs.rs
> +    pub vp_token:String,
수정하였음.

2022-02-09 07:39 UTC, path0509 commented on contracts/campaign/src/executions.rs
> +                amount: campaign_config.vp_burn_amount * qualify_result.vp_burn_rate,
수정하였음

2022-02-09 08:50 UTC, path0509 commented on contracts/campaign_manager/src/entrypoints.rs
> +    migrations::v1_0_8(deps, env, msg)
수정하였음.

2022-02-10 06:57 UTC, jdekim43 approved these changes

2022-02-11 00:21 UTC, merged